### ISSUE TITLE
problem when assigning values into a column

### ISSUE THREAD

**Issue by Tech-Amol5278** [Shreyas3108/Decodr13_Apr#1]
from geopy.geocoders import Nominatim  # to library to work on Geo

# addition of new column in df
df['locations'] = 'NA'
# updating locations column with concatenation of lat and longs
df.locations = df["Lat"].astype(str) +","+ df["Long_"].astype(str) 
## 
geolocator = Nominatim(user_agent="Covid analysis")
# creating new column and assinging the values usling geo locater
# expecting address details
df['address'] = df['locations'].apply(lambda x: geolocator.reverse(x) )

Error:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/usr/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1317                 h.request(req.get_method(), req.selector, req.data, headers,
-> 1318                           encode_chunked=req.has_header('Transfer-encoding'))
   1319             except OSError as err: # timeout error

19 frames
/usr/lib/python3.6/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1253         """Send a complete request to the server."""
-> 1254         self._send_request(method, url, body, headers, encode_chunked)
   1255 

/usr/lib/python3.6/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1299             body = _encode(body, 'body')
-> 1300         self.endheaders(body, encode_chunked=encode_chunked)
   1301 
.....

**Comment by Shreyas3108** [comment]
Closed :Will cover in the class
